### ISSUE TITLE
Documentation should [version-format] be [format]

### ISSUE THREAD

**Issue by stecullum** [PaulHatch/semantic-version#105]
The Readme document uses `version_format` should this be `format` ?

```
  with:
    # A string to determine the format of the version output
    version_format: "${major}.${minor}.${patch}-prerelease${increment}"
```

**Comment by PaulHatch** [comment]
Hey @stecullum, not anymore. As of v5 "format" still works, but [will log a warning](https://github.com/PaulHatch/semantic-version/blob/master/src/main.ts#L56).
