### ISSUE TITLE
Bug in git command for the Default Last Release Resolver

### ISSUE THREAD

**Issue by jswanso** [PaulHatch/semantic-version#112]
I am getting the following error: "**No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote**" on a repository that have tags pulled down.

I believe the issue is at [this line of code](
https://github.com/PaulHatch/semantic-version/blob/d3ce4be04294e5d92f364f87cf4e4289da88553f/src/providers/DefaultLastReleaseResolver.ts#L43) in DefaultLastReleaseResolver.ts file. The `git for-each-ref --sort=-v:*refname --format=%(refname:short) ` command needs to have quotes around the `--format` argument. 

I am running this plugin on a Alpine Docker image with git. This runs in a `sh` shell. When the git command isn't quoted the shell throws a "syntax error: unexpected (" message. If I use a command like `git for-each-ref --sort=-v:*refname --format="%(refname:short)"` it returns a list of values which the code expects. I haven't actually run the code at this point, but am able to verify the behavior of the git command with and without the quotes.

Second, the code has design issues at [this line of code](https://github.com/PaulHatch/semantic-version/blob/d3ce4be04294e5d92f364f87cf4e4289da88553f/src/providers/DefaultLastReleaseResolver.ts#L52) which is the reason I get a false error message. A whole bunch of code is in a try catch block where the real exception is just eaten. Then some false exception is reasoned and shown. It is not helpful to eat the exception because the only way to figure out what is going on is to reverse engineer the code base.

I would love to use this plugin, but this is a blocker.

**Comment by PaulHatch** [comment]
Alpine is not officially supported at this time by GitHub Actions and while it's certainly possible to get it to work and there are a few community supported provisioning options, without official support this isn't something I have time for right now. There's an open issue on the official repo to add this, but there doesn't seem to be much action on it recently.

Using quotes here has caused issues in the past, any such change would need to be free of side effects.
