### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by amardeepprajapati** [PaulHatch/semantic-version#115]
- Enhancement to increment minor , major, patch using branch name instead of commit message.
- Also like major and minor pattern if possible can have patch pattern also.

**Comment by PaulHatch** [comment]
Hello @amardeepprajapati,
These are two issues and both are duplicates. The first is #76, currently on hold. The second is #69, which is now available in v5.1.0 but only for repositories using "bump each commit" mode. For an explanation of why this is please look at some of the previous discussions on this topic.
