### ISSUE TITLE
How to use format to contain the bumped version?

### ISSUE THREAD

**Issue by Vadorequest** [PaulHatch/semantic-version#12]
I'm using the current `format` as such:

```
yml
format: "${major}.${minor}.${patch}-${{ env.GITHUB_REF_SLUG }}"
```

Which yields a `version` such as `1.0.0-v2-mst-aptd-gcms-lcz-sty`.

The problem is that it doesn't increase the `patch` value. When I make multiple releases, it overrides the existing release because the `version` is the same. I thought about using `increment`, but I don't really understand its purpose/usefulness. I'm just expecting the `patch` to increase on its own.

- https://github.com/UnlyEd/next-right-now/actions?query=workflow%3A%22Auto+release%22 Recent releases
- https://github.com/UnlyEd/next-right-now/releases All releases (they override each other)

Is my configuration/usage unexpected? See https://github.com/UnlyEd/next-right-now/blob/380b0bfc1709df1f638cb27f5733e32a2dc833f8/.github/workflows/auto-git-release.yml

_P.S: I'm using the lib on another app that doesn't have a generic `v1`, so there shouldn't be any tags priority at play here._

**Comment by PaulHatch** [comment]
There are two concepts here--one is the format for the output version, the other is the version tag. I should probably make this clearer in the docs, but here's an explanation:

This action is designed to solve the scenario where it is not known whether or not the commit being built will be version released by predicting (but not changing) what the next version value _would be_. With this in mind, you'll expect to have multiple commits for which the same version has been predicted and this is where the increment value comes into play. The increment value shows you basically the count of consecutive commits the same version number has been provided for. This can be used to generate Docker tags for example. You might have versions `2.3.3-preview-0`, `2.3.3-preview-1`, and `2.3.3-preview-2`. Later you decide to release `2.3.3-preview-2` so you tag it `v2.3.3` and tag that image just `2.3.3`. We never expect to see the increment value in a tag, there is no mechanism to pull this value from a tag, so we never expect to see tags like `2.3.3-preview-0` for example, only `2.3.3` or `v2.3.3`.

This is where you'll use the formatted version output. You'll tag a NuGet package or Docker image or the name of a binary or tar file, the artifact of your build. Using the format parameter you can format this however you like interpolating the major/minor/patch/increment values, or you could just reference the output values of the action and format the value elsewhere.

The version tag on the other hand is the tag expected on the git repo. This value is opinionated; it supports only a prefix and optional `-${namespace}` suffix intended to allow multiple versions to be tracked in the same repository using some static text to identify tags for this action. The link generated by the action (just written to the log) includes the tag expected for your configuration.

You could set `v2-mst-aptd-gcms-lcz-sty` as the namespace here, though if you're only tracking one version this isn't necessary. In any event it doesn't need to match the output format.

**Comment by Vadorequest** [comment]
Is it possible to add an option to bump the patch version? Or is it against the philosophy of this lib?

I don't really have a use for `increment`, for real releases. It might be useful for pre-releases but that's it. So, I'd need a way to bump the patch version automatically.

What I want, eventually, is to have something like `v2.0.1-v2-mst-aptd-gcms-lcz-sty` and then when I push another commit without any particular major/minor it'd become `v2.0.2-v2-mst-aptd-gcms-lcz-sty`.

Is that possible with the current implementation?

**Comment by PaulHatch** [comment]
It is generally not what I had in mind, but this is the second request for this in a week, so I've gone ahead and added this in PR #13. You can use `bump_each_commit` in version [v3.2](https://github.com/PaulHatch/semantic-version/releases/tag/v3.2) and you will get this behavior. With this enabled, each commit will bump the version as if it had been tagged.

**Comment by Vadorequest** [comment]
Thank you very much! Using those 2 features, I was able to fix my automated releases on both my projects. 🎉 ❤️
