### ISSUE TITLE
'enable_prerelease_mode' is being ignored when bump_each_commit is enabled

### ISSUE THREAD

**Issue by eldir** [PaulHatch/semantic-version#122]
My understanding is that when pre-release mode is enabled versioning should maintain a 0.x.x formatting. However despite the flag being set adding the trigger word to a commit will raise the version to 1.x.x.

Am I misunderstanding what this flag is intended to do?

**Comment by PaulHatch** [comment]
You are correct, that should not be happening, the expected behavior is that when prerelease mode is enabled

The behavior is validated with [this test](https://github.com/PaulHatch/semantic-version/blob/v5.2.1/src/main.test.ts#L961C2-L961C2):
```
test('Pre-release mode does not update major version if major version is 0', async () => {
    const repo = createTestRepo({ tagPrefix: '', versionFormat: "${major}.${minor}.${patch}", enablePrereleaseMode: true });

    repo.makeCommit('Initial Commit');
    expect((await repo.runAction()).formattedVersion).toBe('0.0.1');
    repo.makeCommit('Second Commit (MINOR)');
    expect((await repo.runAction()).formattedVersion).toBe('0.0.1');
    repo.makeCommit('Third Commit (MAJOR)');
    expect((await repo.runAction()).formattedVersion).toBe('0.1.0');
    repo.exec('git tag 0.1.0');
    repo.makeCommit('Fourth Commit (MAJOR)');
    expect((await repo.runAction()).formattedVersion).toBe('0.2.0');
}, timeout);
```

One thing to check though, are you using something like `True` or `TRUE` perhaps rather than `true` in your config? The next release makes boolean settings case-insensitive, but at the moment only lowercase `true` is recognized.

**Comment by eldir** [comment]
Just checked, it is 'true'
![image](https://github.com/PaulHatch/semantic-version/assets/5166778/3c70cb38-d647-4641-8ba5-cb580c6ec941)

**Comment by eldir** [comment]
Just recreated the issue on a playground repo:
![image](https://github.com/PaulHatch/semantic-version/assets/5166778/33f8853b-beda-477c-a27d-57785d4f63a3)

the v0.0.1 tag is created manually, the auto create appends a build number for us
this is the snip from the workflow file
![image](https://github.com/PaulHatch/semantic-version/assets/5166778/1394ee89-86e5-4ebe-8083-d082ffd5dff2)

**Comment by PaulHatch** [comment]
Ok, I see the issue, bump_each_commit mode is not supporting prerelease mode. I'll add a fix in the next release.

**Comment by eldir** [comment]
> Ok, I see the issue, bump_each_commit mode is not supporting prerelease mode. I'll add a fix in the next release.

Understood. I've turned it off for now, but now see a different issue in that increments don't happen for beta builds.
![image](https://github.com/PaulHatch/semantic-version/assets/5166778/7464b07d-cccc-408a-891e-ea16f29e44b9)
Despite two [MINOR] and one [MAJOR] change the beta build still gets a 0.2.0 version number. Any idea what could be causing this? The workflow is still identical to the one I posted above save for commented out `# bump_each_commit: true`

**Comment by PaulHatch** [comment]
A fix for the issue above is now available in [`v5.3.0`](https://github.com/PaulHatch/semantic-version/releases/tag/v5.3.0) so I am going to close this issue. @eldir could you open a discussion for the second question you asked here?

Regarding your followup question, something doesn't seem right here, it should definitely not be giving you 0.2.0 in any case, but this isn't enough information for me to go on. Could you [create diagnostic](https://github.com/PaulHatch/semantic-version/blob/master/contributing.md#creating-diagnostic-information) for this and include your configuration? Just make sure before posting that non-public email addresses aren't included...I'm planning to add automatic redaction for this in the future, but right now this has to be done manually.

**Comment by eldir** [comment]
Brilliant thanks a lot @PaulHatch!
I'll raise a separate issue for my other question.

**Comment by eldir** [comment]
Actually, having a look at it with fresh eyes, I found the problem for the above. I accidentally deleted the check out from the versioning job in my workflow when I added the test job before that. So all on me.
