### ISSUE TITLE
Node16 deprecated message 

### ISSUE THREAD

**Issue by ViacheslavKudinov** [PaulHatch/semantic-version#133]
Hello @PaulHatch 
according to GitHub blog post https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
and Action logs we get when using the Action:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: paulhatch/semantic-version@v5.3.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
it will be great to get the version with Node20 under the hood.

Probably it has to be smooth to update Node tov20 due to good compartibility between versions.

Thank you in advance 🙏🏻

**Comment by PaulHatch** [comment]
Thanks @ViacheslavKudinov, this update is available in [5.4.0](https://github.com/PaulHatch/semantic-version/releases/tag/v5.4.0).
