### ISSUE TITLE
Update to Node 20?

### ISSUE THREAD

**Issue by jdvor** [PaulHatch/semantic-version#138]
Steps using paulhatch/semantic-version@v5.3.0 produce deprecation warnings (above $GITHUB_STEP_SUMMARY).

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: paulhatch/semantic-version@v5.3.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by PaulHatch** [comment]
Yes, upgrade to [v5.4.0](https://github.com/PaulHatch/semantic-version/releases/tag/v5.4.0) which uses Node 20 as reported in #133.
