### ISSUE TITLE
Tags not created

### ISSUE THREAD

**Issue by datapolitical** [PaulHatch/semantic-version#14]
I've implemented this on my website and the code is running fine, the "version" is updated apparently, but no tags are being created. The documentation doesn't make clear what I'm supposed to do next, and the output just gives a link saying "if you'd like to create a release click this link." 

I don't want to create a release I want it to happen automatically. Or at least, to create a tag.

What I thought this software would do is create updated version tags each time I pushed a patch. I'd then use another tool to create a full release every time there was minor or major change. I don't understand why that's not happening.

What would be extremely helpful is a full example of how this works in the context of building, deploying and releasing, a file that shows you where this code fits in the process and, critically, what comes after it. I have no doubt with a full example I could figure this out quickly. But I don't know what's supposed to come next.

https://github.com/datapolitical/chrisfnicholson.github.io/runs/1615103791?check_suite_focus=true

Thanks for creating this!

Edit: Here's the relevant section of the workflow response

```
Run paulhatch/semantic-version@v3.2
  with:
    branch: main
    tag_prefix: v
    major_pattern: (MAJOR)
    minor_pattern: (MINOR)
    format: ${major}.${minor}.${patch}-prerelease.${increment}
    short_tags: true
    bump_each_commit: false
v2.0
Version is 2.1.0+1
To create a release for this version, go to https://github.com/datapolitical/chrisfnicholson.github.io/releases/new?tag=v2.1&target=main```

**Comment by PaulHatch** [comment]
This action does not create tags, you can use another action such as [create-release](https://github.com/actions/create-release) to create the tag during your build.

If you are doing this, I would consider setting `bump_each_commit` to true, then setting the `tag_prefix` to something that _won't_ match your tag. The reason for this is that if the action is setting tags automatically and you have multiple commits triggering actions simultaneously you'll run into consistency issues.

```
with:
    tag_prefix: manual
    bump_each_commit: false
    ...
```

With this configuration your "v2.0.0" tags will be ignored, but each commit will increment the version. If you did want to set the version for a particular commit (to initialize a specific version for example) you could create a tag "manual2.0.0".

**Comment by datapolitical** [comment]
This is really helpful, thank you! My concern with create release is that it seems like I'd want to run it conditionally, on a version update like 2.1.1 but not 2.1.1-b4. 

And it asks for things like GitHub.ref for the tag which don't seem to be the same as "version". So I'm not sure if I just drop version in there or if that's a *very bad idea*. 

I'm not sure why I'd want to ignore my v2.0.0 tags.

**Comment by PaulHatch** [comment]
Ah, if you're creating them releases conditionally then no, you would not want to ignore them.

You'd probably rather use the commit hash to create the tag/release (I might update the link generated in a future release), but since you want the release to happen automatically, you do need some mechanism to ensure consistency regardless.

When you are releasing manually you can just count on yourself not to simultaneously create two releases. When this is happening automatically you need to take into consideration the fact that you could have a build complete and reach the "automatic release" step, which would mess up the subsequent release. I don't believe there is a mechanism available in GitHub actions to perform this versioning atomically.

**Comment by datapolitical** [comment]
Wouldn't you then just increment the subsequent release? Like, I'm the only one developing for this but I do have an action that runs that updates the site automatically, but those changes shouldn't trigger new releases. 

But even if they did, I guess my way of thinking of it is, as long as the "build and deploy" script that does the versioning and release can't run at the same time as itself I should be fine, no?

And that's what I use this section of code to do. It forces the script to wait until everything else is a green check:

```
Run WyriHaximus/github-action-wait-for-status@v1.2
  with:
    ignoreActions: build_and_deploy
    checkInterval: 10
  env:
    GITHUB_TOKEN: ***```

**Comment by PaulHatch** [comment]
As long as they don't run at the same time you should be fine.

**Comment by datapolitical** [comment]
Awesome! Thank you so much for your prompt help!
