### ISSUE TITLE
Allow multiple patterns

### ISSUE THREAD

**Issue by emre1702** [PaulHatch/semantic-version#17]
When I first read "major_pattern" or "minor_pattern", I thought you'd be able to pass a Regex pattern.
After it didn't work, I looked into the code and found out it's a simple "line.contains(pattern)", so you are not able to use multiple patterns.

So my suggestion would be to allow it either with regex (maybe a second option like major_pattern_regex) or with an array.
With regex we would have many more options.

**Comment by PaulHatch** [comment]
That's an interesting idea, I had not considered this previously but it could be useful in some situations.

I'm wary of adding complexity to the configuration, I'd probably keep the existing inputs but treat values wrapped with `/` as regular expression patterns.

**Comment by PaulHatch** [comment]
Added in [v3.3](https://github.com/PaulHatch/semantic-version/releases/tag/v3.3)
