### ISSUE TITLE
Issue using match pattern

### ISSUE THREAD

**Issue by luisgomsa** [PaulHatch/semantic-version#25]
short_tags: false never find a tag

The command used to find the long tag name: git describe --tags --abbrev=0 --match=v[0-9]+\.[0-9]+\.[0-9]+

never finds for example this v0.1.1

**Comment by PaulHatch** [comment]
Added fix in [v4.0.1](https://github.com/PaulHatch/semantic-version/releases/tag/v4.0.1) to use `*` "zero or more" wildcard instead of `+`.

**Comment by luisgomsa** [comment]
Good work, thanks!
