### ISSUE TITLE
Support for tags which include '/'

### ISSUE THREAD

**Issue by night0wl** [PaulHatch/semantic-version#29]
The tag parsing currently breaks if the tag schema includes `/` e.g. `component/1.0.0`

This is due to [line 82](https://github.com/PaulHatch/semantic-version/blob/master/index.js#L82) which splits the latest matching tag using `split('/')`, and then on line [line 84](https://github.com/PaulHatch/semantic-version/blob/master/index.js#L84) where it extracts a substring using the length of the tag prefix as the index. If the prefix includes a `/` then the final element is already missing the prefix. This means that the actual version numbers are lost and so the test on [line 92](https://github.com/PaulHatch/semantic-version/blob/master/index.js#L92) fails.

In my testing, the tag string printed to the console on line 81 is already the base name, however, I assume that in some cases it may be `refs/tags/v1.0.0` etc. Regardless, splitting on `/` isn't strictly necessary as all but the final element of the split is discarded anyway.

A simple solution would be perhaps to split on the prefix and only use `/` if no prefix exists. E.g:

```
let tagParts = tag.split(tagPrefix === '' ? '/' : tagPrefix)
```

 This would automatically strip the prefix (if one exists) so no need to substring, and would always give a 1 or 2 element array with either `["1.0.0"]`, `["refs/tags/", "1.0.0"]`, or `["", "1.0.0"]`. The rest of the code should then work as expected.

**Comment by PaulHatch** [comment]
Fixed in [v4.0.2](https://github.com/PaulHatch/semantic-version/releases/tag/v4.0.2), thanks for reporting this issue 👍
