### ISSUE TITLE
Does change_path support exclusions?

### ISSUE THREAD

**Issue by discentem** [PaulHatch/semantic-version#31]
I've realized that `semantic-version` considers changes to `.github/workflows` worthy of a new release tag (because by default it consider all the files). Instead of specifying every directory I want to include, I'd rather just specify an exclusion for workflow changes. 

Please let me know if I thinking about this incorrectly though. Should I use a different action to bail on the release if all that's changed is the workflow?

**Comment by PaulHatch** [comment]
The `change_path` parameter is just passed to git, so it should be possible using exclusion syntax [as documented under pathspec](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec):

```
change_path: '. ":^.github/workflow"'
```

**Comment by PaulHatch** [comment]
^ as to your question on releases, I'd say in principle if you change your workflow you might get a different result, potentially resulting in the same version being associated with two different artifacts...but that's really your call. Many/most CI systems traditionally kept the build configuration in a separate database which could be changed without any kind of audit trail baked into either source or artifacts...so while code-defined builds are an improvement in my opinion in keeping these two connected, it is hardly unheard of to version them separately.

Also I'd wonder how often the pipeline even changes as a percentage of commits on a project, and what's being gained by excluding build changes from getting an increment, but again your call.

**Comment by discentem** [comment]
@PaulHatch Thanks for your detailed reply. You make some great points! 

> Many/most CI systems traditionally kept the build configuration in a separate database which could be changed without any kind of audit trail baked into either source or artifacts...so while code-defined builds are an improvement in my opinion in keeping these two connected

I also agree this is a massive improvement. I basically wanted to avoid creating multiple releases while initially tuning the workflows; see below. 

> Also I'd wonder how often the pipeline even changes as a percentage of commits on a project

The answer is probably very low over time. However, when I was initially tuning my Github Actions it was annoying to see a bunch of releases get created just because `.github/workflows` had changed (while tuning). But I ended up just testing my workflows in a fork to solve this annoyance. Once I was happy with them I send a pull request to the main project, merged to master, and created one/the first release 👍
