### ISSUE TITLE
support for searching major/minor patterns also in body of the PR not only subject

### ISSUE THREAD

**Issue by GiuseppeChiesa-TomTom** [PaulHatch/semantic-version#35]
Hello, 

it would be nicer if the action can support the major/minor patterns also in the body of the PR.

Usually when a PR is merged the subject is autogenerated and contains the merge statement with the branch name. 
The tag instead is typically placed in the body of the PR (where the commits are also listed). 

I see here: https://github.com/PaulHatch/semantic-version/blob/cdc37631c1f442c154dd0c198900980e4d9b415e/index.js#L177 the action is retrieving only the subject of the PR. It would be better to also include the body ("%b") so that the pattern is recognised even in the PR description.

**Comment by anthonyscata-wesfarmers** [comment]
Is there any update to this issue?

**Comment by PaulHatch** [comment]
@anthonyscata-wesfarmers I'm planning to release version 5 this weekend (April 2nd/3rd), which will enable support for this.

**Comment by PaulHatch** [comment]
This is available in v5.0.0-alpha, set `search_commit_body` to true to enable
