### ISSUE TITLE
Last Version Tag is incorrect

### ISSUE THREAD

**Issue by thepragmaticprogrammer1** [PaulHatch/semantic-version#49]
Hi Paul,
Great action.

I have the following scenario in GIT:
![image](https://user-images.githubusercontent.com/92262920/162942419-fb9c23cf-e5c4-4c46-b5a9-bb0f5ce51f68.png)
On calculating the versions for ReleaseBranch1 ClassLibrary2v0.3.0 tag is ignored and ClassLibrary2v0.2.0 is selected as the last version.
the tag is definitely in ReleaseBranch1
![image](https://user-images.githubusercontent.com/92262920/162942996-64d74b77-09fc-4eba-b866-4bb1ef1c96b4.png)

I think this is due to TagLastReleaseResolver.ts using $(current)~1. If I change this to $(current) ClassLibrary2 is correctly patched to v0.3.1

**Comment by PaulHatch** [comment]
Hi @smartmelonsystems, thanks for reporting this. I see the issue, dropping `~1` does fix this case, but there are some other edge cases that still need to be handled. Working on a fix for the v5 GA release.

**Comment by PaulHatch** [comment]
Fixed in [v5.0.0-alpha2](https://github.com/PaulHatch/semantic-version/releases/tag/v5.0.0-alpha2), this fix introduces a new breaking change for version 5. Going forward the default mechanism for identifying the most recent commit is going to use the version number rather than the date.

**Comment by smartmelonsystems** [comment]
many thanks Paul for the quick turnaround.
