### ISSUE TITLE
do you have an example using gradle?

### ISSUE THREAD

**Issue by warleyvods** [PaulHatch/semantic-version#53]
Hi, first thanks for contributing your code. My question is: do you have an example repository that uses gradle? I'm not able to apply using the documentation, I'm a little beginner.

**Comment by PaulHatch** [comment]
I will eventually publish a few examples, but these will be of various release workflows and probably not specific to technology stacks, as "using gradle" is outside the scope of this action. The output of this action can be injected into another step as an environment variable. From that point your (Gradle specific) build step wouldn't care/know that the value came from another step, it's just an environment variable as far as that step is concerned.
