### ISSUE TITLE
Add output to tell which kind of version change was made (major,minor,patch)

### ISSUE THREAD

**Issue by sconix** [PaulHatch/semantic-version#62]
Would be nice to have an output that tells what kind of version change was made so that info can be used for some other automation. For example we have a step which we only want to run if major version was changed.

**Comment by Hathoute** [comment]
Is it possible to make intermediate tags before releasing version 5.0.0? I went on the assumption that this is already included in the 5.0.0-alpha2 since it was documented in the Actions Marketplace.

For now I forked your repository and created a temporary action.

**Comment by PaulHatch** [comment]
Hey @Hathoute, yes, sorry I've been traveling + moving internationally, and just getting settled back in now after a crazy couple of weeks. There's a new tagged version, [v5.0.0-beta](https://github.com/PaulHatch/semantic-version/releases/tag/v5.0.0-beta), which includes this output.
