### ISSUE TITLE
Generates warning about set-output command being deprecated

### ISSUE THREAD

**Issue by scouten-adobe** [PaulHatch/semantic-version#66]
I used this action in a [recent workflow](https://github.com/adobe/xmp-toolkit-rs/actions/runs/3291504965/jobs/5425744060#step:5:13) and it generated a warning:

> Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by PaulHatch** [comment]
Release [v5.0.0-beta](https://github.com/PaulHatch/semantic-version/releases/tag/v5.0.0-beta) includes an update from @dusda to use the latest version of actions/core which internally uses the new method to set outputs.

**Comment by scouten-adobe** [comment]
Confirmed fixed in our project. Thank you!
