### ISSUE TITLE
[Question] how to use minor_pattern for AB#

### ISSUE THREAD

**Issue by dtcMLOps** [PaulHatch/semantic-version#72]
Hi @PaulHatch,

Thanks for this life saving tool.

I was wondering how can I use the `minor_pattern` to match commits messages with the following format:

```yaml
AB#000000 feat: myfeature                     --> minor release type
AB#000000 feat!: myfeature breaking change    --> major release type
```

AB# could have any number.

I have used:

```yaml
minor_pattern: "AB#/[0-9]/g feat:"
```

but, it seems is not detecting the pattern in my commit message and only patch number is increased.

I have also used this format:
```yaml
minor_pattern: "AB# feat:"
```

After sending the commit messages as: `AB# feat: my message` this works, so I suspect my error is related with the regex pattern

**Comment by PaulHatch** [comment]
Hey @dtcMLOps, glad you find this useful.

To use a regular expression as a major/minor pattern parameter, you need to wrap the entire argument in a pair of `/`, then it will be interpreted as a regular expression.

Flags can be provided using the `major_regexp_flags` and `minor_regexp_flags` parameters respectively. We probably should have used the JavaScript syntax here, might add support for this in the future, but for now they are specified as a separate parameter/

As you can see in the relevant source [here](https://github.com/PaulHatch/semantic-version/blob/master/src/providers/DefaultVersionClassifier.ts#L21), the default (and right now only) version classifier is checking the pattern string for `pattern.startsWith('/') && pattern.endsWith('/')`.

It's a bit early in my day for me to be writing regex, but something like this should work for you:

```
major_pattern: "/^AB#[0-9]+ feat!:.*$/"
major_regexp_flags: "g"
minor_pattern: "/^AB#[0-9]+ feat:.*$/"
minor_regexp_flags: "g"
```

**Comment by dtcMLOps** [comment]
Hi @PaulHatch, it works like a charm now.

Thanks for such a quick response.
