### ISSUE TITLE
current commit output is not set

### ISSUE THREAD

**Issue by dtcMLOps** [PaulHatch/semantic-version#81]
Hi @PaulHatch 

Greetings.

I noticed there is bug in a new feature in the latest version 5.0.1 regarding the output `current_commit`

![Screenshot from 2022-12-31 04-37-31](https://user-images.githubusercontent.com/115469901/210132035-a7cab613-ac06-4a36-a510-c374694658b5.png)

I went to check the latest output options [here](https://github.com/PaulHatch/semantic-version/blob/v5.0.1/dist/index.js#:~:text=core.setOutput(%22lastVersion%22%2C%20authors)%3B) and it seems is not set that property.

**Comment by PaulHatch** [comment]
Thanks, the mapping for this value from the result object to the action's output was missing. This has been added and is available in v5.0.2
