### ISSUE TITLE
Is the readme accurate?

### ISSUE THREAD

**Issue by tgillitzer** [PaulHatch/semantic-version#85]
It seems like it is outdated?   For instance, formatted_version is in it, but there are no other instances of that string in the repo.

I'm trying to understand how PR branches might be versioned, which it seems like there is no automatic handling of that.   Is that correct?
The intended use is to specify different version_format strings for PR runs vs runs against a release (main) branch?

**Comment by PaulHatch** [comment]
It is up to date. The input you mention should have been `version_format` and has been corrected.

This action specifically uses only the repo currently, though I am considering loosening that restriction starting in v5.1.0 to allow the version type (major/minor/patch) to be pulled from PR tags.

Having said that a PR is just another commit on a branch as far as the build is concerned, there's nothing special about them but you do have a different build action on PRs available and you can do whatever you want with this information there. You can implement a versioning strategy however you like. Generally until merged a PR is not part of the release, not everyone even builds artifacts, but there's nothing stopping you from creating a version for it. You could for example use the predicted version and add the branch name as a pre-release tag like: `{major}.{minor}.{patch}-{branchName}+{commitHash}`. This is just an example, note that the branch name is not provided as an output from this action.

I am in the process of writing a guide that include some complete examples of various versioning/release strategies that you may find helpful.
