### ISSUE TITLE
[Feature request] output for previous version as tag

### ISSUE THREAD

**Issue by dtcMLOps** [PaulHatch/semantic-version#92]
Hi @PaulHatch,

Hope you find very well.

I have been using this awesome tool and it is working fantastic. I was wondering if could be possible in a future release to have a new output for the previous version with the same format as `version_tag`. The thing is that we have a semantic previous version which is fine, but I have to re-create the previous tag using the semantic version.

Could be something like:

- previous_version -->   0.0.1
- version_tag -->            v0.2.0
- previous_version_tag --> v0.0.1

So we will have an output in the same "tag" format to be used in other jobs.

**Comment by PaulHatch** [comment]
Hey @dtcMLOps,
Glad you are finding this useful. Yeah, it is probably going to be either next week or the week after before I have another chance to update this action, but I think this can be added for version 5.1.0.

**Comment by PaulHatch** [comment]
Released in v5.1.0
